# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lukas/Projects/Github/lukaskellerstein/FinanceApp/finance_app/ui/windows/main/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pageBox = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageBox.sizePolicy().hasHeightForWidth())
        self.pageBox.setSizePolicy(sizePolicy)
        self.pageBox.setObjectName("pageBox")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pageBox.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pageBox.addWidget(self.page_2)
        self.gridLayout.addWidget(self.pageBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuAssets = QtWidgets.QMenu(self.menubar)
        self.menuAssets.setObjectName("menuAssets")
        self.menuWatchlists = QtWidgets.QMenu(self.menubar)
        self.menuWatchlists.setObjectName("menuWatchlists")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuDebug = QtWidgets.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStocksAsset = QtWidgets.QAction(MainWindow)
        self.actionStocksAsset.setObjectName("actionStocksAsset")
        self.actionFuturesAsset = QtWidgets.QAction(MainWindow)
        self.actionFuturesAsset.setObjectName("actionFuturesAsset")
        self.actionStocksWatchlist = QtWidgets.QAction(MainWindow)
        self.actionStocksWatchlist.setObjectName("actionStocksWatchlist")
        self.actionFuturesWatchlist = QtWidgets.QAction(MainWindow)
        self.actionFuturesWatchlist.setObjectName("actionFuturesWatchlist")
        self.actionOptionsWatchlist = QtWidgets.QAction(MainWindow)
        self.actionOptionsWatchlist.setObjectName("actionOptionsWatchlist")
        self.actionHomePage = QtWidgets.QAction(MainWindow)
        self.actionHomePage.setObjectName("actionHomePage")
        self.actionThreads = QtWidgets.QAction(MainWindow)
        self.actionThreads.setObjectName("actionThreads")
        self.actionManual_Calc = QtWidgets.QAction(MainWindow)
        self.actionManual_Calc.setObjectName("actionManual_Calc")
        self.actionRealtimeData = QtWidgets.QAction(MainWindow)
        self.actionRealtimeData.setObjectName("actionRealtimeData")
        self.menuAssets.addAction(self.actionStocksAsset)
        self.menuAssets.addAction(self.actionFuturesAsset)
        self.menuWatchlists.addAction(self.actionStocksWatchlist)
        self.menuWatchlists.addAction(self.actionFuturesWatchlist)
        self.menuWatchlists.addAction(self.actionOptionsWatchlist)
        self.menuHome.addAction(self.actionHomePage)
        self.menuDebug.addAction(self.actionThreads)
        self.menuDebug.addAction(self.actionRealtimeData)
        self.menuOptions.addAction(self.actionManual_Calc)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuAssets.menuAction())
        self.menubar.addAction(self.menuWatchlists.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())

        self.retranslateUi(MainWindow)
        self.pageBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CellarstoneTradingApp"))
        self.menuAssets.setTitle(_translate("MainWindow", "Assets"))
        self.menuWatchlists.setTitle(_translate("MainWindow", "Watchlists"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuDebug.setTitle(_translate("MainWindow", "Debug"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionStocksAsset.setText(_translate("MainWindow", "Stocks"))
        self.actionFuturesAsset.setText(_translate("MainWindow", "Futures"))
        self.actionStocksWatchlist.setText(_translate("MainWindow", "Stocks"))
        self.actionFuturesWatchlist.setText(_translate("MainWindow", "Futures"))
        self.actionOptionsWatchlist.setText(_translate("MainWindow", "Options"))
        self.actionHomePage.setText(_translate("MainWindow", "HomePage"))
        self.actionThreads.setText(_translate("MainWindow", "Threads"))
        self.actionManual_Calc.setText(_translate("MainWindow", "Manual Calc"))
        self.actionRealtimeData.setText(_translate("MainWindow", "Realtime data"))
